#!/usr/bin/env bash
GROUPID=`id -g`
USERID=`id -u`
# TODO:
# -o: overwrite entrypoint with shell?
# -i: use useradd and groupadd to impersonate the host machine's user.
if [ $# -lt 1 ]; then
    echo "You must specify a docker image to work with!"
    exit -1;
fi
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME:$HOME -v $PWD:$PWD -w $PWD $1 /bin/bash -c "groupadd -f -g $GROUPID intruder && useradd -N -o -u $USERID -g $GROUPID -G root,staff -d $HOME -s /bin/bash intruder && su intruder"
